import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <div className='container'>
        <header>
          <h1>My Next Page</h1>
        </header>
        {children}
        </div>
        <footer>
          <p>&copy; {new Date().getFullYear()}</p>
        </footer>
      </body>
    </html>
  );
}